
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class Tbplayer
{
    private readonly System.Collections.Generic.Dictionary<int, demo.player> _dataMap;
    private readonly System.Collections.Generic.List<demo.player> _dataList;
    
    public Tbplayer(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.player>(count);
        _dataList = new System.Collections.Generic.List<demo.player>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.player _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.player.Deserializeplayer(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.player> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.player> DataList => _dataList;

    public demo.player GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.player Get(int key) => _dataMap[key];
    public demo.player this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

