
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum Color
    {
        /// <summary>
        /// 红
        /// </summary>
        RED = 1,
        /// <summary>
        /// 绿
        /// </summary>
        GREEN = 2,
        /// <summary>
        /// 蓝
        /// </summary>
        BLUE = 3,
        /// <summary>
        /// 白
        /// </summary>
        WHITE = 4,
    }

} 

