
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MonsterConfig : Luban.BeanBase
{
    public MonsterConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["monsterInfo"].IsObject) { throw new SerializationException(); }  MonsterInfo = global::cfg.Monster.DeserializeMonster(_buf["monsterInfo"]);  }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
    }

    public static MonsterConfig DeserializeMonsterConfig(JSONNode _buf)
    {
        return new MonsterConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly Monster MonsterInfo;
    public readonly string Icon;
   
    public const int __ID__ = -55174244;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        MonsterInfo?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "monsterInfo:" + MonsterInfo + ","
        + "icon:" + Icon + ","
        + "}";
    }
}
}

