
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Monster : Luban.BeanBase
{
    public Monster(JSONNode _buf) 
    {
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
    }

    public static Monster DeserializeMonster(JSONNode _buf)
    {
        return new Monster(_buf);
    }

    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
   
    public const int __ID__ = -1393696838;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "name:" + Name + ","
        + "level:" + Level + ","
        + "}";
    }
}
}

