
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbMonster TbMonster {get; }
    public demo.Tbplayer Tbplayer {get; }
    public demo.Tbitem Tbitem {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbMonster = new TbMonster(loader("tbmonster"));
        Tbplayer = new demo.Tbplayer(loader("demo_tbplayer"));
        Tbitem = new demo.Tbitem(loader("demo_tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbMonster.ResolveRef(this);
        Tbplayer.ResolveRef(this);
        Tbitem.ResolveRef(this);
    }
}

}
