
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbMonster
{
    private readonly System.Collections.Generic.Dictionary<int, MonsterConfig> _dataMap;
    private readonly System.Collections.Generic.List<MonsterConfig> _dataList;
    
    public TbMonster(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, MonsterConfig>(count);
        _dataList = new System.Collections.Generic.List<MonsterConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MonsterConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.MonsterConfig.DeserializeMonsterConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MonsterConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<MonsterConfig> DataList => _dataList;

    public MonsterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public MonsterConfig Get(int key) => _dataMap[key];
    public MonsterConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

